[package]
name = "ic-ec"
description = "X25519, Ed25519, and elliptic-curve arithmetic for IronCrypto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[features]
default = ["std"]
std = ["ic-core/std", "ic-hash/std", "ic-mac/std"]

[dependencies]
ic-core = { workspace = true }
ic-hash = { workspace = true }
ic-mac = { workspace = true }
