//! RSA signatures, in pure Rust with no dependencies outside this workspace.
//!
//! # Scope
//!
//! - [`RsaPublicKey`] / [`RsaPrivateKey`] built from big-endian components, or
//!   generated by [`key::generate`].
//! - RSASSA-PKCS1-v1_5 signing and verification (RFC 8017 §8.2).
//! - RSASSA-PSS signing and verification (RFC 8017 §8.1).
//!
//! Encryption is deliberately absent. RSAES-PKCS1-v1_5 is a Bleichenbacher
//! oracle waiting to happen, and RSAES-OAEP is worth having only if there is a
//! caller for it; key transport is better served by the ECDH and (later) ML-KEM
//! paths. Signature verification is the operation the world actually needs from
//! RSA, because it is what certificate chains are made of.
//!
//! # Sizes
//!
//! 2048, 3072, and 4096-bit moduli. Anything below 2048 is refused outright
//! rather than offered with a warning, per SP 800-131A.
//!
//! # Example
//!
//! Marked `no_run` because generating a 2048-bit key takes seconds; in a real
//! program the key comes from storage, via
//! [`RsaPrivateKey::from_components`].
//!
//! ```no_run
//! # fn main() -> ic_core::Result<()> {
//! use ic_rsa::{generate, Pkcs1Sha256, PssSha256};
//! let mut rng = ic_drbg::Rng::from_os()?;
//! let key = generate(2048, &mut rng)?;
//!
//! let mut signature = [0u8; 256];
//! Pkcs1Sha256::sign(&key, b"message", &mut signature)?;
//! Pkcs1Sha256::verify(key.public_key(), b"message", &signature)?;
//!
//! PssSha256::sign(&key, b"message", &mut rng, &mut signature)?;
//! PssSha256::verify(key.public_key(), b"message", &signature)?;
//! # Ok(())
//! # }
//! ```

#![cfg_attr(not(feature = "std"), no_std)]
#![forbid(unsafe_code)]
#![deny(missing_docs)]

mod kat;
pub mod key;
pub mod pkcs1;
pub mod pss;
pub mod uint;

pub use key::{generate, RsaPrivateKey, RsaPublicKey, MAX_MODULUS_BITS, MIN_MODULUS_BITS};
pub use pkcs1::{Pkcs1Sha256, Pkcs1Sha384, Pkcs1Sha512};
pub use pss::{PssSha256, PssSha384, PssSha512};

#[cfg(test)]
mod testkey;
