[package]
name = "ic-mac"
description = "HMAC, CMAC, KMAC, and Poly1305 message authentication for IronCrypto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["std"]
std = ["ic-core/std", "ic-hash/std", "ic-cipher/std"]

[dependencies]
ic-core = { workspace = true }
ic-hash = { workspace = true }
ic-cipher = { workspace = true }
