"""Generate testvectors/openssl-ml-dsa-pkcs8.json: ML-DSA private keys in each
of RFC 9881's three PKCS#8 forms, written by OpenSSL.

    python scripts/gen_mldsa_pkcs8.py > testvectors/openssl-ml-dsa-pkcs8.json

Needs `openssl` 3.5 or later on the PATH. For each parameter set and seed,
`openssl genpkey -pkeyopt hexseed:` makes the key, and `openssl pkey
-provparam ml-dsa.output_formats=` writes it as seed-only, priv-only (the
expanded key) and seed-priv (both). The expanded key is also recorded on its
own, from `openssl pkey -text`, so a test can check a parser's view of each
form against OpenSSL's rather than against itself.
"""

import json
import os
import re
import subprocess
import sys
import tempfile

SETS = ["ML-DSA-44", "ML-DSA-65", "ML-DSA-87"]
SEEDS = [bytes(range(32)).hex(), bytes(range(0xa0, 0xc0)).hex()]
FORMS = {"seed-only": "seed", "priv-only": "expanded", "seed-priv": "both"}


def run(*args):
    return subprocess.run(args, check=True, capture_output=True).stdout


def text_field(text, name):
    m = re.search(name + r":\n((?:\s+[0-9a-f:]+\n)+)", text)
    return re.sub(r"[\s:]", "", m.group(1))


def main():
    version = run("openssl", "version").decode().strip()
    cases = []
    with tempfile.TemporaryDirectory() as tmp:
        for ps in SETS:
            for seed in SEEDS:
                pem = os.path.join(tmp, "k.pem")
                run("openssl", "genpkey", "-algorithm", ps, "-pkeyopt", f"hexseed:{seed}", "-out", pem)
                # OpenSSL on Windows ends its text output's lines with CRLF.
                text = run("openssl", "pkey", "-in", pem, "-text", "-noout").decode()
                text = text.replace(chr(13), "")
                assert text_field(text, "seed") == seed, "OpenSSL kept a different seed"
                case = {"parameter_set": ps, "seed": seed, "expanded_key": text_field(text, "priv")}
                for fmt, field in FORMS.items():
                    der = os.path.join(tmp, f"{fmt}.der")
                    run("openssl", "pkey", "-in", pem, "-outform", "DER", "-out", der,
                        "-provparam", f"ml-dsa.output_formats={fmt}")
                    case[f"pkcs8_{field}"] = open(der, "rb").read().hex()
                cases.append(case)
    json.dump({
        "algorithm": "ml-dsa PKCS#8 private keys, all three parameter sets",
        "source": f"{version}, generated by scripts/gen_mldsa_pkcs8.py: per set and seed, "
                  "openssl genpkey -algorithm <set> -pkeyopt hexseed:<seed>; openssl pkey "
                  "-text -noout for the expanded key; openssl pkey -outform DER -provparam "
                  "ml-dsa.output_formats=seed-only|priv-only|seed-priv for the three RFC 9881 "
                  "forms. An independent implementation, not a NIST vector.",
        "cases": cases,
    }, sys.stdout, indent=1)
    print()


if __name__ == "__main__":
    main()
