"""Convert NIST's ACVP DRBG files into this repository's vector format.

    python scripts/gen_drbg_vectors.py <acvp-dir> > testvectors/drbg.json
    python scripts/gen_drbg_vectors.py <acvp-dir> --rust crates/ic-drbg/src/kat.rs

The second form writes the known-answer cases the DRBG self-tests run: the
first case without prediction resistance for CTR_DRBG and for HMAC_DRBG over
SHA-256, as Rust constants, so that what the self-test holds is NIST's value
copied by a program and not by hand.

<acvp-dir> holds, for each of ctrDRBG-1.0 and hmacDRBG-1.0, the files
`<name>-prompt.json` and `<name>-expectedResults.json`, as downloaded from
https://github.com/usnistgov/ACVP-Server at commit 975de31eb83d
(gen-val/json-files/<name>/). Each is checked against the SHA-256 below.

Kept: the groups for mechanisms this library has -- CTR_DRBG over AES-256
without a derivation function, and HMAC_DRBG over each hash `ic_mac` has an
HMAC for -- with and without prediction resistance, every case of each.
Dropped: AES-128, AES-192 and TDES, CTR_DRBG with a derivation function, and
HMAC_DRBG over SHA-1, SHA-224, SHA-512/224, SHA3-224 and SHA3-384.

A case is a fixed sequence, which the script checks before flattening it:

- without prediction resistance: instantiate, reseed, generate, generate;
- with it: instantiate, generate, generate, each generate drawing entropy.

`returned` is the output of the second generate; the first is discarded.

Nothing here computes a cryptographic value.
"""

import hashlib
import json
import os
import sys

PINNED = {
    "ctrDRBG-1.0-prompt.json": "35a2fda242abd3e8e9c6c89a2878ee1d4d499c48",
    "ctrDRBG-1.0-expectedResults.json": "46608d7bbcaf0f6408a1905f81a77d3e2e90bfd5",
    "hmacDRBG-1.0-prompt.json": "3613b3b990904ed9c98ea05ce223e660e29d45f3",
    "hmacDRBG-1.0-expectedResults.json": "0d3a6e0d7bed5ef84ab9f2a27a0ad04b9478b386",
}

# ACVP's mode -> this library's name for the mechanism.
HMAC = {"SHA2-256": "hmac-drbg-sha2-256", "SHA2-384": "hmac-drbg-sha2-384",
        "SHA2-512": "hmac-drbg-sha2-512", "SHA2-512/256": "hmac-drbg-sha2-512-256",
        "SHA3-256": "hmac-drbg-sha3-256", "SHA3-512": "hmac-drbg-sha3-512"}


def load(directory, name):
    out = []
    for part in ("prompt", "expectedResults"):
        file = f"{name}-{part}.json"
        with open(os.path.join(directory, file), "rb") as f:
            raw = f.read()
        digest = hashlib.sha256(raw).hexdigest()
        if not digest.startswith(PINNED[file]):
            raise SystemExit(f"{file}: SHA-256 {digest} is not the pinned file")
        doc = json.loads(raw)
        out.append(doc[1] if isinstance(doc, list) else doc)
    prompt, expected = out
    answers = {(g["tgId"], t["tcId"]): t for g in expected["testGroups"] for t in g["tests"]}
    return prompt, answers


def mechanism(name, group):
    if name == "ctrDRBG-1.0":
        return "ctr-drbg-aes-256" if group["mode"] == "AES-256" and not group["derFunc"] else None
    return HMAC.get(group["mode"])


def flatten(group, test, answer, algorithm):
    steps = test["otherInput"]
    uses = [s["intendedUse"] for s in steps]
    if group["predResistance"]:
        assert uses == ["generate", "generate"], uses
        reseed = {"additionalInput": "", "entropyInput": ""}
        first, second = steps
        assert first["entropyInput"] and second["entropyInput"]
    else:
        assert uses == ["reSeed", "generate", "generate"], uses
        reseed, first, second = steps
        assert reseed["entropyInput"] and not first["entropyInput"] and not second["entropyInput"]
    returned = answer["returnedBits"]
    assert len(returned) * 4 == group["returnedBitsLen"]
    return {"algorithm": algorithm,
            "prediction_resistance": "true" if group["predResistance"] else "false",
            "entropy": test["entropyInput"].lower(), "nonce": test["nonce"].lower(),
            "personalization": test["persoString"].lower(),
            "reseed_entropy": reseed["entropyInput"].lower(),
            "reseed_additional": reseed["additionalInput"].lower(),
            "generate1_entropy": first["entropyInput"].lower(),
            "generate1_additional": first["additionalInput"].lower(),
            "generate2_entropy": second["entropyInput"].lower(),
            "generate2_additional": second["additionalInput"].lower(),
            "returned": returned.lower()}


RUST_FIELDS = ["entropy", "nonce", "personalization", "reseed_entropy", "reseed_additional",
               "generate1_additional", "generate2_additional", "returned"]


def write_rust(path, cases):
    out = ["//! Known-answer cases for the DRBG self-tests, from NIST's ACVP vectors.",
           "//!",
           "//! Generated by `scripts/gen_drbg_vectors.py --rust` from the files that",
           "//! script pins; edit the script, not this file. Each is the first case",
           "//! without prediction resistance of its group, and is also in",
           "//! `testvectors/drbg.json`, where the vector test runs it with the rest.",
           "",
           "/// One case: instantiate, reseed, generate, generate. `returned` is the",
           "/// output of the second generate.",
           "pub(crate) struct Kat {"]
    out += [f"    pub(crate) {f}: &'static str," for f in RUST_FIELDS]
    out += ["}", ""]
    for algorithm, name in [("ctr-drbg-aes-256", "CTR_AES_256"),
                            ("hmac-drbg-sha2-256", "HMAC_SHA2_256")]:
        case = next(c for c in cases if c["algorithm"] == algorithm
                    and c["prediction_resistance"] == "false")
        out += [f"/// `{algorithm}`.", f"pub(crate) const {name}: Kat = Kat {{"]
        out += [f'    {f}: "{case[f]}",' for f in RUST_FIELDS]
        out += ["};", ""]
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write("\n".join(out))


def main():
    acvp = sys.argv[1]
    cases = []
    for name in ("ctrDRBG-1.0", "hmacDRBG-1.0"):
        prompt, answers = load(acvp, name)
        for group in prompt["testGroups"]:
            algorithm = mechanism(name, group)
            if algorithm is None:
                continue
            assert group["reSeed"], group["tgId"]
            for test in group["tests"]:
                cases.append(flatten(group, test, answers[(group["tgId"], test["tcId"])],
                                     algorithm))
    if "--rust" in sys.argv:
        write_rust(sys.argv[sys.argv.index("--rust") + 1], cases)
        return
    json.dump({
        "algorithm": "SP 800-90A DRBGs: CTR_DRBG(AES-256, no df) and HMAC_DRBG",
        "source": "NIST ACVP-Server, https://github.com/usnistgov/ACVP-Server commit "
                  "975de31eb83d, gen-val/json-files/ctrDRBG-1.0 and hmacDRBG-1.0, converted by "
                  "scripts/gen_drbg_vectors.py. Every case of the groups for mechanisms this "
                  "library has, with and without prediction resistance. `returned` is the "
                  "output of the second generate.",
        "cases": cases,
    }, sys.stdout, indent=1)
    print()
    print(f"{len(cases)} cases", file=sys.stderr)


if __name__ == "__main__":
    main()
