"""Generate crates/ic-ec/tests/ecdsa_prehash.rs: ECDSA signatures over every
curve and SHA-2 hash pairing, for `verify_prehash`.

    python scripts/gen_ecdsa_prehash.py > crates/ic-ec/tests/ecdsa_prehash.rs
    cargo fmt --all

The signatures come from pyca/cryptography's deterministic ECDSA, which
implements RFC 6979 over OpenSSL. The P-256 and P-384 keys are RFC 6979's own
(appendices A.2.5 and A.2.6), so those signatures are the RFC's values for
each hash; this script refuses to run unless it reproduces the four values for
the curves' native hashes that this repository already checks against the RFC
in its unit tests. The P-521 key is fixed here rather than taken from the RFC,
whose P-521 vectors this repository does not use (see p521.rs).
"""

import cryptography
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature

KEYS = {
    "P-256": (ec.SECP256R1(), 32,
              0xC9AFA9D845BA75166B5C215767B1D6934E50C3DB36E89B127B8A622B120F6721),
    "P-384": (ec.SECP384R1(), 48,
              int("6b9d3dad2e1b8c1c05b19875b6659f4de23c3b667bf297ba9aa47740787137d8"
                  "96d5724e4c70a825f872c9ea60d2edf5", 16)),
    # Fixed for this file: the SHA-512 of a label, read as an integer and kept
    # below the order by dropping its top bits.
    "P-521": (ec.SECP521R1(), 66, None),
}

HASHES = [("SHA-224", hashes.SHA224()), ("SHA-256", hashes.SHA256()),
          ("SHA-384", hashes.SHA384()), ("SHA-512", hashes.SHA512())]

# Values the repository's unit tests take from RFC 6979 (p256.rs, p384.rs).
RFC = {
    ("P-256", "SHA-256", b"sample"):
        "efd48b2aacb6a8fd1140dd9cd45e81d69d2c877b56aaf991c34d0ea84eaf3716"
        "f7cb1c942d657c41d436c7a1b6e29f65f3e900dbb9aff4064dc4ab2f843acda8",
    ("P-256", "SHA-256", b"test"):
        "f1abb023518351cd71d881567b1ea663ed3efcf6c5132b354f28d3b0b7d38367"
        "019f4113742a2b14bd25926b49c649155f267e60d3814b4c0cc84250e46f0083",
}
RFC_PREFIX = {
    ("P-384", "SHA-384", b"sample"): "94edbb92a5ecb8aad4736e56c691916b3f88140666ce9fa73d64c4ea95ad133c",
    ("P-384", "SHA-384", b"test"): "8203b63d3c853e8d77227fb377bcf7b7b772e97892a80f36ab775d509d7a5feb",
}


def p521_scalar():
    d = hashes.Hash(hashes.SHA512())
    d.update(b"IronCrypto ecdsa_prehash P-521 key")
    return int.from_bytes(d.finalize(), "big") >> 2


def main():
    rows = []
    for curve, (crv, width, scalar) in KEYS.items():
        if scalar is None:
            scalar = p521_scalar()
        key = ec.derive_private_key(scalar, crv)
        pub = key.public_key().public_numbers()
        sec1 = "04" + pub.x.to_bytes(width, "big").hex() + pub.y.to_bytes(width, "big").hex()
        for hname, h in HASHES:
            for msg in (b"sample", b"test"):
                d = hashes.Hash(type(h)())
                d.update(msg)
                digest = d.finalize()
                der = key.sign(msg, ec.ECDSA(type(h)(), deterministic_signing=True))
                r, s = decode_dss_signature(der)
                sig = r.to_bytes(width, "big").hex() + s.to_bytes(width, "big").hex()
                want = RFC.get((curve, hname, msg))
                if want is not None and sig != want:
                    raise SystemExit(f"does not reproduce RFC 6979 for {curve} {hname} {msg}")
                prefix = RFC_PREFIX.get((curve, hname, msg))
                if prefix is not None and not sig.startswith(prefix):
                    raise SystemExit(f"does not reproduce RFC 6979 for {curve} {hname} {msg}")
                rows.append((curve, hname, msg.decode(), sec1, digest.hex(), sig))

    print(HEADER.format(version=cryptography.__version__))
    print("const CASES: &[Case] = &[")
    for curve, hname, msg, sec1, digest, sig in rows:
        print("    Case {")
        print(f'        curve: "{curve}",')
        print(f'        hash: "{hname}",')
        print(f'        message: "{msg}",')
        print(f'        public_key: "{sec1}",')
        print(f'        digest: "{digest}",')
        print(f'        signature: "{sig}",')
        print("    },")
    print("];")
    print(FOOTER)


HEADER = '''//! `verify_prehash` against signatures made with every SHA-2 hash on every
//! curve: the pairings X.509 and other protocols use besides each curve's own.
//!
//! GENERATED by `scripts/gen_ecdsa_prehash.py` with pyca/cryptography
//! {version} (OpenSSL 3.5.7), whose deterministic ECDSA implements RFC 6979.
//! The P-256 and P-384 keys are RFC 6979's (appendices A.2.5 and A.2.6), and
//! the generator refuses to run unless it reproduces the RFC values for those
//! curves' native hashes that `p256.rs` and `p384.rs` already check, so these
//! are the RFC's signatures for each hash. The P-521 key is the generator's
//! own. Regenerate rather than edit.
//!
//! The digests cover both of FIPS 186-5's cases: shorter than the group order,
//! used whole (SHA-224 on every curve, SHA-512 on P-521), and longer, truncated
//! to the order's width (SHA-384 and SHA-512 on P-256, SHA-512 on P-384).

use ic_core::codec::hex_decode;
use ic_ec::p256::EcdsaP256Sha256;
use ic_ec::p384::EcdsaP384Sha384;
use ic_ec::p521::EcdsaP521Sha512;

struct Case {{
    curve: &'static str,
    hash: &'static str,
    message: &'static str,
    public_key: &'static str,
    digest: &'static str,
    signature: &'static str,
}}
'''

FOOTER = '''
fn bytes(hex: &str) -> Vec<u8> {
    let mut out = vec![0u8; hex.len() / 2];
    hex_decode(hex.as_bytes(), &mut out).expect("hex");
    out
}

fn verify(curve: &str, pk: &[u8], digest: &[u8], sig: &[u8]) -> ic_core::Result<()> {
    match curve {
        "P-256" => EcdsaP256Sha256::verify_prehash(pk, digest, sig),
        "P-384" => EcdsaP384Sha384::verify_prehash(pk, digest, sig),
        "P-521" => EcdsaP521Sha512::verify_prehash(pk, digest, sig),
        _ => unreachable!("{curve}"),
    }
}

/// The narrowest digest each curve accepts: as strong as the curve.
fn min_len(curve: &str) -> usize {
    match curve {
        "P-256" => 32,
        "P-384" => 48,
        _ => 64,
    }
}

/// Every pairing at least as strong as its curve verifies, and the curve's
/// own pairing agrees with `verify`. Every weaker pairing -- SHA-224 on any
/// curve, SHA-256 on P-384 and P-521, SHA-384 on P-521 -- is refused for its
/// width, although the signature is valid.
#[test]
fn every_strong_enough_pairing_verifies_and_weaker_ones_are_refused() {
    use ic_core::traits::SignatureScheme;
    let (mut verified, mut refused) = (0, 0);
    for case in CASES {
        let (pk, digest, sig) = (bytes(case.public_key), bytes(case.digest), bytes(case.signature));
        let result = verify(case.curve, &pk, &digest, &sig);
        if digest.len() < min_len(case.curve) {
            let err = result.expect_err("a digest weaker than the curve");
            assert_eq!(err.kind(), ic_core::ErrorKind::InvalidLength, "{} {}", case.curve, case.hash);
            refused += 1;
            continue;
        }
        result.unwrap_or_else(|e| panic!("{} {} {}: {e:?}", case.curve, case.hash, case.message));
        let native = matches!(
            (case.curve, case.hash),
            ("P-256", "SHA-256") | ("P-384", "SHA-384") | ("P-521", "SHA-512")
        );
        if native {
            let m = case.message.as_bytes();
            match case.curve {
                "P-256" => EcdsaP256Sha256::verify(&pk, m, &sig),
                "P-384" => EcdsaP384Sha384::verify(&pk, m, &sig),
                _ => EcdsaP521Sha512::verify(&pk, m, &sig),
            }
            .expect("the message form agrees");
        }
        verified += 1;
    }
    // Per message: P-256 accepts 3 hashes, P-384 2, P-521 1.
    assert_eq!((verified, refused), (12, 12), "the cases did not run");
}

/// A signature is bound to the part of its digest FIPS 186-5 uses, and to its
/// own bytes and message; the part of a digest beyond the order's width is not
/// used, so changing it must change nothing.
///
/// The second half is the rule the truncation implements, tested against the
/// rule rather than a value: a digest longer than the order contributes only
/// its leftmost order-width bits, so bytes past them are ignored.
#[test]
fn a_wrong_digest_key_or_signature_is_refused() {
    let mut beyond_checked = 0;
    for case in CASES.iter().filter(|c| c.digest.len() / 2 >= min_len(c.curve)) {
        let (pk, digest, sig) = (bytes(case.public_key), bytes(case.digest), bytes(case.signature));
        // Bytes of the order: 32, 48, 66.
        let order_bytes = sig.len() / 2;
        let used = digest.len().min(order_bytes);
        for at in [0, used / 2, used - 1] {
            let mut d = digest.clone();
            d[at] ^= 1;
            assert!(verify(case.curve, &pk, &d, &sig).is_err(), "digest byte {at}");
        }
        for at in used..digest.len() {
            let mut d = digest.clone();
            d[at] ^= 0xff;
            verify(case.curve, &pk, &d, &sig)
                .unwrap_or_else(|_| panic!("{} {}: byte {at} is past the order", case.curve, case.hash));
            beyond_checked += 1;
        }
        let mut s = sig.clone();
        s[sig.len() - 1] ^= 1;
        assert!(verify(case.curve, &pk, &digest, &s).is_err(), "signature");
        // The other message's signature under the same curve and hash.
        let other = CASES
            .iter()
            .find(|c| c.curve == case.curve && c.hash == case.hash && c.message != case.message)
            .expect("both messages present");
        assert!(verify(case.curve, &pk, &digest, &bytes(other.signature)).is_err(), "message");
    }
    // SHA-384 and SHA-512 on P-256 (16 and 32 bytes past), SHA-512 on P-384
    // (16), for both messages.
    assert_eq!(beyond_checked, 2 * (16 + 32 + 16), "the truncated bytes were not all tried");
}

/// Widths outside SHA-224..SHA-512 are refused before any arithmetic, SHA-1's
/// 20 bytes among them, with the error saying so.
#[test]
fn digest_widths_outside_the_sha2_family_are_refused() {
    let case = &CASES[0];
    let (pk, sig) = (bytes(case.public_key), bytes(case.signature));
    for len in [0usize, 1, 20, 27, 29, 31, 33, 47, 49, 63, 65, 128] {
        let err = verify(case.curve, &pk, &vec![0x5a; len], &sig).expect_err("refused");
        assert_eq!(err.kind(), ic_core::ErrorKind::InvalidLength, "length {len}");
    }
}
'''

if __name__ == "__main__":
    main()
